# Generated by Django 4.1.2 on 2022-10-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamplanner', '0004_alter_user_username'),
        ('dreamplanner', '0004_destination_completed_destination_created_at_and_more'),
    ]

    operations = [
    ]
